services:
  atmos_server:
    container_name: atmos_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      NETFLIX_API_KEY: ${NETFLIX_API_KEY}
      REMO_TOKEN: ${REMO_TOKEN}
    depends_on:
      - atmos_db
    volumes:
      - ./db:/workspace/db
  atmos_db:
    container_name: atmos_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/data:/db
    environment:
      DATABASE_URL: "sqlite:atmos.db"
  atmos_client:
    container_name: atmos_client
    build:
      context: ./client/atmos_extension/
      dockerfile: Dockerfile
    volumes:
      - ./client/atmos_extension/.output:/usr/src/app/.output

