// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Url } from "./Url";

export type AdjustLigtingRequest = { remo_token: string, url: Url, texts: Array<string>, };
