[package]
name = "atmos"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio.workspace = true
color-eyre.workspace = true
atmos_server = { path = "../atmos_server" }
atmos_dict = { path = "../atmos_dict" }
atmos_config = { path = "../atmos_config" }
