name: Render documents
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        document: [
          {source: "docs/typst/manual.typ", output: "docs/manual.pdf"},
          {source: "docs/typst/design.typ", output: "docs/design.pdf"}
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile ${{ matrix.document.source }} ${{ matrix.document.output }}
